### ISSUE TITLE
Kukła Villagera umiera po użyciu Laski Niebios oraz Laski Bólu

### ISSUE THREAD

**Issue by Sonnelus** [Sonnelus/laina.pl#1]

**Comment by sh4rk9999** [comment]
^ Jeżeli użyje się Laski Niebios i od razu po niej Laski Bólu to kukła Villagera umiera

**Comment by Sonnelus** [comment]
Poprawiono kod. Do przetestowania

**Comment by sh4rk9999** [comment]
Teraz nie umiera, ale za to zamienia się w wiedźmę

**Comment by Sonnelus** [comment]
Poprawiono: pioruny powinny już nie móc przemieniać Kukły villagera w wiedźmę. Do przetestowania

**Comment by Sonnelus** [comment]
Przetestowane, działa wszystko okej
