### ISSUE TITLE
Dispenser na Iluzjonerze

### ISSUE THREAD

**Issue by Sonnelus** [Sonnelus/laina.pl#14]
na iluzjonerze da się otworzyć dispenser ze strzałami, które się nie kończą, więc jest to źródło nieskończonej ilości strzał

**Comment by Sonnelus** [comment]
Poprawione - do sprawdzenia.

**Comment by sh4rk9999** [comment]
Sprawdzone, dispensera nie da się już otworzyć ale nie wystrzeliwuje w ogóle strzał

**Comment by Sonnelus** [comment]
Poprawiono, do przetestowania

**Comment by sh4rk9999** [comment]
Wszystko działa tak jak powinno
