### ISSUE TITLE
Rubinowy sklepik

### ISSUE THREAD

**Issue by sh4rk9999** [Sonnelus/laina.pl#15]
w rubinowym sklepiku dalej widnieje książka, która daje "exp" zamiast maestrii

**Comment by sh4rk9999** [comment]
W jednej z ukrytych skrzynek w Toni Trytona również dalej można znaleźć książke, która daje exp zamiast maestrii

**Comment by Sonnelus** [comment]
Poprawione, zarówno w sklepiku, jak i Toni Trytona
