### ISSUE TITLE
Quest "Piękny dzień na wędkowanie!"

### ISSUE THREAD

**Issue by sh4rk9999** [Sonnelus/laina.pl#17]
W momencie, gdy trzeba złowić 8 łososi, złowione ryby nie naliczają się do postępu zadania

**Comment by Sonnelus** [comment]
W którym etapie zadania?

**Comment by sh4rk9999** [comment]
Sprawdzone, w 2 etapie złowione łososie normalnie naliczają się do postępu zadania
