### ISSUE TITLE
Laska Niebios, Laska Zatrucia, Laska Odpędzenia oraz Laska Bólu nie działają w Dungeonach

### ISSUE THREAD

**Issue by sh4rk9999** [Sonnelus/laina.pl#2]

**Comment by Sonnelus** [comment]
Poprawiono kod. Do przetestowania

**Comment by sh4rk9999** [comment]
Laska Niebios (jedyny problem jest taki, że ogień z tej laski może spalić drewno na Iluzjonerze), Laska Zatrucia i Laska Bólu działają, a Laska Odpędzenia nie usuwa żadnych efektów. Nie działają jeszcze itemki takie jak Lizak Halloweenowy oraz Choinka

**Comment by Sonnelus** [comment]
Poprawiony kod i do przetestowania czy już działają poprawnie na dungeonach:

1. Laska Odpędzenia
2. Choinka
3. Laska Świętego Mikołaja
4. Lizak Halloweenowy
5. Laska Kapłana
6. Miłosna Kosa

**Comment by Sonnelus** [comment]
+ Kolejna poprawka
