### ISSUE TITLE
Ametystowy pierścień

### ISSUE THREAD

**Issue by Isao121** [Sonnelus/laina.pl#22]
![Image](https://github.com/user-attachments/assets/df68a7f6-9d85-41c3-89ba-dc222e97baf9)
podczas, gdy w opisie itemku jest napisane, że daje on +1 ataku, +2 hp i +2 obrony, to w statystykach itemku pokazuje się, że daje on +1 ataku, +1 armoru oraz +2 hp

**Comment by Sonnelus** [comment]
To opis jest niepoprawny. Został poprawniony i kolejne wygenerowane Ametystowe Pierścienie będą miały prawidłowy opis. Nie da się zmienić istniejących itemków, chyba że poprzez NPC do wymiany, jednak gracze raczej nie będą zachęceni wymianą, która zmienia tylko opis, wręcz przeciwnie - pewnie będą chcieli zachować zbugowaną wersję do kolekcji ;P
