### ISSUE TITLE
Kukła

### ISSUE THREAD

**Issue by Isao121** [Sonnelus/laina.pl#23]
przez moją nieuwagę mając pełne eq kliknąłem żeby kukła wróciła do eq, niestety kukła zniknęła a jajo przepadło

**Comment by Sonnelus** [comment]
Kod poprawiony - powinien uwzględniać teraz pełne EQ i wyrzucać jajko kukły pod nogi. Do sprawdzenia

**Comment by Isao121** [comment]
Sprawdzone, wyrzuca kukłę pod nogi. Zamykam.
