### ISSUE TITLE
Dungeony

### ISSUE THREAD

**Issue by Isao121** [Sonnelus/laina.pl#27]
Wszystkim mobkom na dungeonach (oprócz bossów) HP zresetowało się do domyślnego. (20 hp zombie, szkielety itp, 30 hp strażnicy na trytonie)

**Comment by Sonnelus** [comment]
Do przetestowania czy żadnego moba na żadnym bossie nie pominąłem

**Comment by Isao121** [comment]
Git, wszystko jest jak bylo wczesniej, zamykam.
