### ISSUE TITLE
Mistrz Wiatru

### ISSUE THREAD

**Issue by Isao121** [Sonnelus/laina.pl#28]
Gdy pojawi się HP Bar bossa i dungeon będzie pusty, po czym się wróci, to dungeon nie respi innych wichrzyków.

**Comment by Sonnelus** [comment]
Coś pozmieniałem. Do przetestowania po następnym restarcie serwera.

**Comment by Isao121** [comment]
Sprawdzone, nic sie nie zmienilo. Zapomnialem dodac, ze oprocz braku mniejszych wichrzykow, nie nakladaja sie tez efekty, ktore by sie nakladaly (nie mowie o potkach z dispenserow, te dzialaja tak jak nalezy), m.in lewitacja kiedy zostanie bossowi 25% hp.

**Comment by Isao121** [comment]
Naprawione.
