### ISSUE TITLE
Bezdenne wiadra

### ISSUE THREAD

**Issue by Sonnelus** [Sonnelus/laina.pl#3]
Bezdenne wiadra nie działają na baniaki

**Comment by Isao121** [comment]
Tak jak napisane, gdy próbuję wypełnić kocioł bezdennym wiadrem to nic się nie dzieje.

**Comment by Sonnelus** [comment]
Do przetestowania po restarcie

**Comment by Isao121** [comment]
Sprawdzone, działa jak należy.
