### ISSUE TITLE
Obrazy z halloween

### ISSUE THREAD

**Issue by Isao121** [Sonnelus/laina.pl#31]
![Image](https://github.com/user-attachments/assets/a53c8ac3-8585-48eb-9b4d-24b2f5f46794)

obrazy z halloween w postaci itemkow przestaly funkcjonowac, stackuja sie ze soba. gdy sie je postawi, to nic się nie dzieje, a obraz na chwilę znika z eq. zeby itemek sie znowu pojawil w eq, trzeba otworzyc ekwipunek i nacisnal slot w ktorym obraz zniknal.

**Comment by Sonnelus** [comment]
Obrazy straciły niestety nazwy. Nie ma na to rady poza wymianą itemków.
