### ISSUE TITLE
Customowe itemki + ramki na przedmioty

### ISSUE THREAD

**Issue by Sonnelus** [Sonnelus/laina.pl#4]
m.in. Bezdennych wiader nie da się włożyć do Item Frame

**Comment by Isao121** [comment]
Bezdenną lawę da się włożyć, bezdenną wodę nie. Reszta customowych itemków powinna być możliwa do umieszczenia w item frame, stestowane na parunastu itemkach.

**Comment by Sonnelus** [comment]
Do przetestowania: Bezdenne Wiadro Wody -> Ramka na przedmiot (po restarcie)

**Comment by Sonnelus** [comment]
Przetestowane
