### ISSUE TITLE
Zatruta Katana

### ISSUE THREAD

**Issue by Sonnelus** [Sonnelus/laina.pl#6]
Zatruta katana zabiera dmg na spawnie

**Comment by Sonnelus** [comment]
Sprawdzić czy inne miecze nakładające withering bądź zatrucie też tego nie robią:
Przeklęty Miecz
Przeklęty Topór
Zatruty Miecz
Zatruty Bastard
Witherowy Bastard

**Comment by Isao121** [comment]
Przetestowane, żaden z mieczy nie zadaje obrażeń na spawnie.

**Comment by Sonnelus** [comment]
Zamykam wątek
