### ISSUE TITLE
Custom Kilofy o większym zasięgu

### ISSUE THREAD

**Issue by sh4rk9999** [Sonnelus/laina.pl#7]
Custom Kilofy o większym zasięgu kopiąc na granicy działek innego gracza potrafią zniszczyć bloki tego gracza

EDIT: Kilofy, siekiery oraz łopaty z serii "ucznia", "czeladnika" oraz "mistrza" niszczą teren gracza gdy skopie się blok przed działką w linii prostej. Tytanowy kilof został przetestowany i jest w porządku.

**Comment by Sonnelus** [comment]
Poprawiono kod. Do przetestowania

**Comment by Isao121** [comment]
Stestowane, działa. Custom kilofy już nie niszczą czyichś działek.
